from core.rbac.role import *
from core.rbac.user import *

APIS = {
    # APPID -> APPKEY
    # APPKEY generated by: echo "$(date) + $appid" | md5sum
    "prod": "9cdaccb0f61a66ac70cfd5256cd8960b"
}

USERS = Users()
USERS.add("guest", "guestpw", [GUEST])
USERS.add("staff", "staffpw", [STAFF])
USERS.add("dev", "devpw", [GUEST, STAFF])
USERS.add("admin", "adminpw", [ADMIN])
